service: s3-csv-lambda

provider:
  name: aws
  runtime: python3.9
  region: us-east-1

functions:
  getCsv:
    handler: handler.lambda_handler
    events:
      - http:
          path: tickets
          method: post
          cors: true

plugins:
  - serverless-python-requirements
